//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumView
    {
        public string Title { get; set; }
        public string Artist_Name { get; set; }
        public int Year { get; set; }
        public Nullable<int> Rating { get; set; }
        public int AlbumId { get; set; }
    }
}
