//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongView
    {
        public int SongID { get; set; }
        public string Title { get; set; }
        public string Artist { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Genre { get; set; }
        public string Album { get; set; }
        public int Track { get; set; }
        public int Track_Length_Seconds { get; set; }
    }
}
