USE [CDCatalog]
GO
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (1, N'Alternative Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (2, N'College Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (3, N'Experimental Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (4, N'Goth Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (5, N'Grunge')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (6, N'Hardcore Punk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (7, N'Hard Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (8, N'Indie Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (9, N'New Wave')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (10, N'Progressive Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (11, N'Punk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (12, N'Shoegaze')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (13, N'Steampunk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (14, N'Anime')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (15, N'Acoustic Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (16, N'Chicago Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (17, N'Classic Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (18, N'Contemporary Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (19, N'Country Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (20, N'Delta Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (21, N'Electric Blues')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (22, N'Lullabies')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (23, N'Sing-Along')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (24, N'Stories')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (25, N'Avant-Garde')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (26, N'Baroque')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (27, N'Chamber Music')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (28, N'Chant')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (29, N'Choral')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (30, N'Classical Crossover')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (31, N'Early Music')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (32, N'High Classical')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (33, N'Impressionist')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (34, N'Medieval')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (35, N'Minimalism')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (36, N'Modern Composition')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (37, N'Opera')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (38, N'Orchestral')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (39, N'Renaissance')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (40, N'Romantic')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (41, N'Wedding Music')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (42, N'Alternative Country')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (43, N'Americana')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (44, N'Bluegrass')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (45, N'Contemporary Bluegrass')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (46, N'Contemporary Country')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (47, N'Country Gospel')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (48, N'Honky Tonk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (49, N'Outlaw Country')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (50, N'Traditional Bluegrass')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (51, N'Traditional Country')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (52, N'Urban Cowboy')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (53, N'Breakbeat')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (54, N'Dubstep')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (55, N'Exercise')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (56, N'Garage')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (57, N'Hardcore')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (58, N'Hard Dance')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (59, N'Hi-NRG/Eurodance')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (60, N'House')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (61, N'Jackin House')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (62, N'Jungle/Drum''n''bass')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (63, N'Techno')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (64, N'Trance')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (65, N'Bop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (66, N'Lounge')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (67, N'Swing')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (68, N'Ambient')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (69, N'Crunk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (70, N'Downtempo')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (71, N'Electro')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (72, N'Electronica')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (73, N'Electronic Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (74, N'IDM/Experimental')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (75, N'Industrial')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (76, N'Alternative Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (77, N'Bounce')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (78, N'Dirty South')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (79, N'East Coast Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (80, N'Gangsta Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (81, N'Hardcore Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (82, N'Hip-Hop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (83, N'Latin Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (84, N'OldSchool Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (85, N'Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (86, N'Underground Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (87, N'West Coast Rap')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (88, N'Environmental')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (89, N'Healing')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (90, N'Meditation')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (91, N'Nature')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (92, N'Relaxation')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (93, N'Travel')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (94, N'Adult Contemporary')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (95, N'Britpop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (96, N'Pop/Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (97, N'Soft Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (98, N'Teen Pop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (99, N'Contemporary R&B')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (100, N'Disco')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (101, N'Doo Wop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (102, N'Funk')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (103, N'Motown')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (104, N'Neo-Soul')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (105, N'Quiet Storm')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (106, N'Soul')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (107, N'Reggae')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (108, N'Barbershop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (109, N'Standards')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (110, N'Traditional Pop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (111, N'Vocal Jazz')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (112, N'Vocal Pop')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (113, N'Adult Alternative')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (114, N'American Trad Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (115, N'Arena Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (116, N'Blues-Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (117, N'British Invasion')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (118, N'Death Metal/Black Metal')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (119, N'Glam Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (120, N'Hair Metal')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (121, N'Metal')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (122, N'Jam Bands')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (123, N'Prog-Rock/Art Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (124, N'Psychedelic')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (125, N'Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (126, N'Roots Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (127, N'Singer/Songwriter')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (128, N'Southern Rock')
INSERT [dbo].[Genre] ([GenreId], [GenreName]) VALUES (129, N'Surf')